export const browserCoreExamples = [
  "genoma browser status",
  "genoma browser start",
  "genoma browser stop",
  "genoma browser tabs",
  "genoma browser open https://example.com",
  "genoma browser focus abcd1234",
  "genoma browser close abcd1234",
  "genoma browser screenshot",
  "genoma browser screenshot --full-page",
  "genoma browser screenshot --ref 12",
  "genoma browser snapshot",
  "genoma browser snapshot --format aria --limit 200",
  "genoma browser snapshot --efficient",
  "genoma browser snapshot --labels",
];

export const browserActionExamples = [
  "genoma browser navigate https://example.com",
  "genoma browser resize 1280 720",
  "genoma browser click 12 --double",
  'genoma browser type 23 "hello" --submit',
  "genoma browser press Enter",
  "genoma browser hover 44",
  "genoma browser drag 10 11",
  "genoma browser select 9 OptionA OptionB",
  "genoma browser upload /tmp/genoma/uploads/file.pdf",
  'genoma browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "genoma browser dialog --accept",
  'genoma browser wait --text "Done"',
  "genoma browser evaluate --fn '(el) => el.textContent' --ref 7",
  "genoma browser console --level error",
  "genoma browser pdf",
];
